language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem install bundler -v 1.14.3
install: bin/setup
